// executions/status.js — estado vivo del proyecto Pine Script
// Cada sesión LEE este archivo al empezar y lo ACTUALIZA al terminar (o antes de agotar tokens).
// Plan completo: plans/pine-script-engine.md
module.exports = {
  updatedAt: "2026-06-16T09:00:00Z",
  currentPhase: 4,
  branch: "pinescript (sale de master@cbdea78=Fase 3; Fases 1-3 estan en master, Fase 4 en adelante en pinescript)",
  done: [
    "Plan aprobado y guardado en plans/pine-script-engine.md",
    "Carpeta executions/ creada con este archivo de estado",
    "Fase 1 COMPLETA: src/lib/pine/ (errors, types, tokens, lexer, ast, parser, analyze, index) + runtime/ (series, context, interpreter, builtins-core/math/ta)",
    "Fase 1: vitest configurado (vitest.config.ts, script npm test) — 56 tests verdes en 4 suites (lexer, parser, interpreter, ta-golden)",
    "Fase 1: golden tests vs src/lib/indicators/{rsi,ema,sma}.ts pasan con tolerancia relativa 1e-8 (mismo nº de puntos)",
    "Fase 1: npm run lint limpio y npx tsc --noEmit limpio",
    "Fase 2 COMPLETA: integración en el chart (scripts del usuario dibujándose en vivo)",
    "Fase 2: chart-store.ts — PineScriptRecord + scripts: PineScriptRecord[] + acciones addScript/updateScript/removeScript/toggleScriptOnChart/toggleScriptHidden + estado efímero addScriptDialogOpen/setAddScriptDialogOpen + scripts en partialize y en merge (default [])",
    "Fase 2: src/hooks/chart/useUserScriptPanes.ts (nuevo) — hook genérico con Map scriptId→{compiled, series[], error}; compile cacheado por source; LineSeries por PlotSpec; overlay→pane 0, no-overlay→scriptBasePaneIdx+offset; hidden vía applyOptions({visible}); updateUserScripts estable con try/catch por script; rebuild total de series al cambiar layoutKey (basePaneIdx/source/inputs/onChart)",
    "Fase 2: PriceChart.tsx — scriptBasePaneIdx = 1 + rsi + macd + (sqzmom||adx), instancia useUserScriptPanes y pasa updateUserScripts a useKlineData",
    "Fase 2: useKlineData.ts — updateUserScripts añadido a KlineDataCallbacks e invocado en los 4 puntos (carga inicial, tick WS, loadMoreHistory, fullRefresh)",
    "Fase 2: src/components/pine/AddScriptDialog.tsx (nuevo, provisional) — nombre opcional (fallback al title de indicator()), textarea monoespaciada 14 filas, diagnostics línea:col en rojo sin cerrar, addScript con onChart=true al compilar; UI en español",
    "Fase 2: IndicatorMenu.tsx — sección 'Mis scripts' con 'Nuevo script Pine…', toggle on/off por script y botón eliminar; contador de activos incluye scripts onChart",
    "Fase 2: AddScriptDialog montado en src/app/page.tsx junto a IndicatorSettingsDialog/PriceLineSettingsDialog/DrawingSettingsDialog",
    "Fase 2: npm run lint limpio, npx tsc --noEmit limpio, npm test 56/56 verdes",
    "Fase 3 COMPLETA: editor CodeMirror 6 + CRUD de scripts (reemplaza el textarea provisional)",
    "Fase 3: deps añadidas con pnpm (NO npm, ver notes): @codemirror/{state,view,language,lint,commands} + @lezer/highlight",
    "Fase 3: src/lib/pine/editor/pine-language.ts (nuevo) — StreamLanguage con tokenizer ~100 líneas (keywords, ns builtins ta./math./input./color./plot., series vars, números, strings, #hex, comentarios //, operadores) + HighlightStyle dark/light acordes a TV_COLORS",
    "Fase 3: src/lib/pine/editor/pine-lint.ts (nuevo) — linter CM con delay 300ms; usa compile() y mapea Diagnostic.start/end (offsets absolutos del lexer) a from/to, clampeados al doc; incluye warnings de analyze() cuando compila ok",
    "Fase 3: src/components/pine/PineEditor.tsx (nuevo) — wrapper CM6 controlado (value/onChange/theme); EditorView creado una vez en useEffect con cleanup view.destroy(); tema vía Compartment; sync externo de value con dispatch",
    "Fase 3: src/components/pine/PineEditorDialog.tsx + ScriptList.tsx (nuevos) — dialog ~90vw/90vh (94dvh móvil) con lista lateral (crear/renombrar inline/duplicar/eliminar con confirm, punto azul = en el chart), input de nombre, botones Guardar / Guardar y añadir al chart (con errores guarda pero NO añade, muestra aviso), confirm al descartar cambios sin guardar",
    "Fase 3: chart-store.ts — addScriptDialogOpen/setAddScriptDialogOpen reemplazados por pineEditorOpen + pineEditorTarget (string|null) + setPineEditorOpen/setPineEditorTarget; addScript ahora devuelve el id y acepta opts {onChart} (default true)",
    "Fase 3: IndicatorMenu.tsx — 'Nuevo script Pine…' abre editor con target null; cada script tiene botón lápiz (editar) además de toggle y eliminar",
    "Fase 3: page.tsx — AddScriptDialog eliminado; PineEditorDialog cargado con next/dynamic ssr:false y montado solo tras la primera apertura (ref everOpened) para no entrar en el chunk inicial",
    "Fase 3: src/components/pine/AddScriptDialog.tsx ELIMINADO",
    "Fase 3: npm run lint limpio, npx tsc --noEmit limpio, npm test 56/56 verdes, npm run build ok",
    "Fase 4 MOTOR COMPLETO (commit c3d056a en rama pinescript): mitad de motor de la Fase 4, 77/77 tests verdes, lint+tsc limpios",
    "Fase 4 motor: analyze.ts extrae InputDef[] {id,type,title,defval,minval,maxval,step,options}; input.int/float/bool/string/color/source + input() genérico (infiere tipo del defval); id = title o 'input{N}' posicional estable; titles duplicados caen a posicional; defval no constante = error de compilación; input.source limitado a open/high/low/close/volume/hl2/hlc3/ohlc4",
    "Fase 4 motor: runScript resuelve input.* por override en el Record inputs → si no, defval; int se clampa a minval/maxval y se redondea; source devuelve la serie elegida",
    "Fase 4 motor: PlotSpec gana style ('line'|'stepline'|'histogram'|'columns'|'area'|'circles'|'cross', default 'line') y linewidth (default 1); color dinámico por barra → cada punto de ScriptResult.plots[].points gana color?:string (hex resuelto)",
    "Fase 4 motor: hline() estática → script.hlines: HLineSpec[] {price,title,color,linestyle}; precio no literal = error 'constante numérica'",
    "Fase 4 motor: plotshape()/plotchar() → script.shapes + ScriptResult.shapes[].points {time,position:'aboveBar'|'belowBar',shape:'arrowUp'|'arrowDown'|'circle',color,text?}; mapeo shape.triangleup→arrowUp, triangledown→arrowDown, circle→circle; location.belowbar/abovebar/absolute→belowBar/aboveBar (absolute→aboveBar con warning); plotchar usa el char como text del marker",
  ],
  inProgress: [
    "Fase 4 UI/RENDER — PENDIENTE (la mitad de motor ya está hecha y commiteada). Falta SOLO la UI:",
    "  (a) useUserScriptPanes.ts: crear series según PlotSpec.style (line/stepline=LineSeries lineType, histogram/columns=HistogramSeries color por punto, area=AreaSeries, circles/cross=LineSeries pointMarkersVisible); hlines→series.createPriceLine (remover en cleanup); shapes→createSeriesMarkers (import de lightweight-charts v5) sobre la 1ª serie del script, refrescar en cada update y limpiar; PASAR script.inputs a runScript; exponer lastValues por scriptId y error por script para las pills",
    "  (b) src/components/pine/ScriptSettingsDialog.tsx (nuevo): dialog autogenerado desde script.inputs (InputDef[]) — int/float→number con min/max/step, bool→switch, string→text o select si options, color→color picker; reutiliza controles de src/components/chart/indicator-settings/shared.tsx; guarda overrides en script.inputs vía updateScript (recalcula solo, layoutKey ya incluye inputs); botón 'Restaurar valores'; usar patrón keyed-body de PineEditorDialog para evitar set-state-in-effect",
    "  (c) chart-store.ts: ampliar settingsTarget de IndicatorKey|null a IndicatorKey|`script:${string}`|null; IndicatorSettingsDialog.tsx enruta 'script:*' al ScriptSettingsDialog (o montarlo aparte)",
    "  (d) Pills: scripts overlay→ChartLegend.tsx, no-overlay→SubPaneLegend.tsx en su pane (usar paneOffsets como RSI/MACD); cada pill (diseño de IndicatorPill.tsx): nombre (title de indicator() o name), último valor del 1er plot, ojo (toggleScriptHidden), engranaje (settingsTarget=`script:id`), X (quitar del chart = onChart:false, NO borra), lápiz (abre editor Pine)",
  ],
  pending: [
    "Fase 5: control de flujo (if/else, for, switch), [a,b]=f(), funciones de usuario, builtins ampliados (ta.macd/bb/kc/linreg/valuewhen/barssince, color.new/rgb) — paridad copy/paste; golden: Squeeze Momentum LazyBear y DMI/ADX ≡ builtins",
    "Fase 6: Drive sync v2 (SyncedState+scripts, version 2 con migración), badges de error en pills, autocomplete de builtins",
  ],
  notes: [
    "API pública: compile(source) → {ok,script|diagnostics}; runScript(script, candles, inputs?, options?) → ScriptResult; runScript LANZA PineRuntimeError (runtime/fuel) — el caller debe capturarlo (useUserScriptPanes ya lo hace)",
    "RunOptions { maxFuelPerBar, maxFuelTotal } expone los límites de fuel (defaults 50k/5M en runtime/context.ts); los tests los bajan para probar el aborto",
    "Semántica implementada: aritmética con na→na, división/módulo por 0→na, comparación con na→false, and/or/not y ternario evalúan AMBOS lados/ramas (estado ta.* consistente, sin cortocircuito), truthiness na/false/0/\"\"→false",
    "var carry-forward: el init de `var` solo corre en barra 0; en barras siguientes arrastra series[bar-1]; `:=` exige slot declarado",
    "builtin `time` devuelve milisegundos UNIX (semántica Pine; Candle.time está en segundos)",
    "hist sobre expresiones no-identificador usa serie oculta por nodeId (ctx.getHiddenSeries); se evalúa la base en cada barra aunque el offset sea na",
    "ta.tr funciona también como variable (member sin llamada) con estado por nodeId — mismo contador que callSiteId en el parser, sin colisiones",
    "analyze(): meta de indicator() (title/shorttitle/overlay literales), PlotSpec por plot() (id=callSiteId, title posicional/nombrado, color de color.* o literal), inputs=[] (estructura lista para Fase 4); falta de indicator()/plot() genera warnings, no errores",
    "Tests golden usan velas sintéticas mulberry32(seed=42), 300 velas, en el propio test (sin fixtures)",
    "Limitación conocida: `not na` → true (Pine real da na); strings usan truthiness estilo JS; input.*/hline/plotshape lanzan error claro 'llega en fase posterior'",
    "FASE 2 — gotchas para la Fase 3:",
    "useUserScriptPanes: el rebuild se decide por layoutKey(basePaneIdx + id/source/inputs de scripts onChart). Cambios de hidden/name NO recrean series (solo applyOptions). Al editar source en Fase 3, updateScript dispara rebuild automático vía layoutKey — no hace falta nada extra",
    "useUserScriptPanes destruye y recrea TODAS las series de scripts cuando cambia el layout (lightweight-charts compacta panes al quitar series intermedias); recomputePaneOffsets se llama en requestAnimationFrame tras cada rebuild (mismo patrón que useRSIPane)",
    "Caché de compile por source (Map, se limpia a >50 entradas). Errores de compile/runtime quedan en entry.error (console.warn, no UI todavía — el badge en pill llega en Fase 6)",
    "El chart se crea UNA sola vez (useChartInit; el tema cambia con applyOptions), por eso layoutKeyRef sobrevive sin invalidarse",
    "AddScriptDialog se monta en src/app/page.tsx (patrón de los otros dialogs globales) y se abre con store.addScriptDialogOpen — en Fase 3 reemplazar por PineEditorDialog y eliminar AddScriptDialog.tsx + considerar si addScriptDialogOpen muere o se renombra",
    "scripts está en partialize y en el deep-merge (p.scripts ?? []) — persiste en localStorage; el sync a Drive llega en Fase 6 (NO está en SyncedState todavía)",
    "Verificación manual Fase 2: npm run dev → Indicadores → 'Nuevo script Pine…' → pegar indicator(\"Mi EMA\", overlay=true) + plot(ta.ema(close, 21), color=color.orange) → línea naranja sobre velas moviéndose con cada tick; versión overlay=false → sub-pane debajo de ADX; toggle de MACD builtin reubica el pane del script; recarga → persiste",
    "FASE 3 — gotchas para la Fase 4:",
    "IMPORTANTE: el proyecto se instala con PNPM, no npm (npm install falla con 'Cannot read properties of null (reading matches)' por el layout .pnpm de node_modules). Usar `pnpm add …`",
    "Las reglas nuevas de eslint react-hooks (set-state-in-effect) prohíben setState síncrono en efectos: PineEditorDialog evita el efecto de carga montando el body keyed por target y solo mientras open (useState lazy initializers); el dirty se reporta al padre vía dirtyRef asignado en render con eslint-disable react-hooks/refs",
    "StreamLanguage: la tabla legacy del stream-parser ya define el nombre de token 'builtin' (→ variableName.standard) y PISA las entradas custom del tokenTable — por eso el token custom se llama 'pineBuiltin'. Nombres estándar (keyword/bool/atom/number/string/comment/operator/punctuation/variableName) resuelven solos contra tags de @lezer/highlight",
    "pine-lint.ts mapea Diagnostic.start/end del motor directamente a from/to de CM (son offsets absolutos 0-based del lexer, verificado); clampea al tamaño del doc y fuerza rango mínimo de 1 char",
    "El chrome del editor usa var(--tv-*) (cambian solos con el tema); solo el flag dark de EditorView.theme y el HighlightStyle se reconfiguran vía Compartment al cambiar store.theme",
    "PineEditorDialog se monta en page.tsx con next/dynamic ssr:false + condición pineEditorOpen||everOpenedRef → el chunk de CodeMirror solo se descarga en la primera apertura (verificado en npm run build: no entra en el chunk inicial)",
    "addScript(name, source, opts?) ahora DEVUELVE el id y acepta {onChart} — duplicar usa onChart:false; 'Guardar' de un script nuevo usa onChart:false y 'Guardar y añadir' onChart:true solo si compila",
    "Para Fase 4: ScriptSettingsDialog puede seguir el patrón keyed-body de PineEditorDialog para evitar set-state-in-effect; settingsTarget del store debe ampliarse a IndicatorKey | `script:<id>` | null",
    "Verificación manual Fase 3: npm run dev → Indicadores → 'Nuevo script Pine…' → editor grande con highlighting; escribir plot(ta.sma(close 14)) → subrayado rojo en la coma faltante (~300ms); Guardar y añadir al chart → aparece en el chart y en la lista con punto azul; lápiz en el menú reabre con el script cargado; renombrar inline (doble click o lápiz en la lista), duplicar y eliminar con confirm; cambiar tema light/dark → el editor cambia de paleta",
  ],
};
